// OAuth Token Service - Automatic token management
import { saveCredential, getCredentials } from '../firebase/firestore';
import { UserCredentials } from '../firebase/types';

export interface AutoTokenResult {
  success: boolean;
  accessToken?: string;
  error?: string;
  platform: string;
}

export class OAuthTokenService {
  // Get Facebook access token automatically
  static async getFacebookToken(): Promise<AutoTokenResult> {
    try {
      // Check session storage for Facebook access token
      const accessToken = sessionStorage.getItem('facebook_access_token');
      
      if (!accessToken) {
        return {
          success: false,
          error: 'No Facebook access token found. Please login with Facebook first.',
          platform: 'facebook'
        };
      }

      return {
        success: true,
        accessToken: accessToken,
        platform: 'facebook'
      };
    } catch (error: unknown) {
      const err = error as Error;
      return {
        success: false,
        error: err.message || 'Failed to get Facebook token',
        platform: 'facebook'
      };
    }
  }

  // Auto-save OAuth tokens to credential vault
  static async saveOAuthTokens(userId: string): Promise<void> {
    try {
      const facebookResult = await this.getFacebookToken();
      
      if (facebookResult.success && facebookResult.accessToken) {
        // Save Facebook token to credential vault
        const facebookCredential: UserCredentials = {
          id: `facebook_${userId}`,
          userId: userId,
          platform: 'facebook',
          accessToken: facebookResult.accessToken,
          tokenType: 'oauth',
          expiresAt: new Date(Date.now() + (3600 * 1000)), // 1 hour from now
          createdAt: new Date(),
          updatedAt: new Date(),
          isActive: true,
          metadata: {
            source: 'oauth',
            autoGenerated: true
          }
        };

        await saveCredential(facebookCredential);
        console.log('Facebook OAuth token saved to credential vault');
      }
    } catch (error) {
      console.error('Error saving OAuth tokens:', error);
    }
  }

  // Get all available OAuth tokens
  static async getAllOAuthTokens(): Promise<{
    facebook?: string;
    instagram?: string;
    linkedin?: string;
  }> {
    const tokens: any = {};

    try {
      // Facebook token
      const facebookResult = await this.getFacebookToken();
      if (facebookResult.success) {
        tokens.facebook = facebookResult.accessToken;
      }
    } catch (error) {
      console.error('Error getting Facebook token:', error);
    }

    // Add other platforms as needed
    return tokens;
  }

  // Check if user has OAuth tokens
  static hasOAuthTokens(): boolean {
    return !!sessionStorage.getItem('facebook_access_token');
  }

  // Clear all OAuth tokens
  static clearAllOAuthTokens(): void {
    sessionStorage.removeItem('facebook_access_token');
    // Clear other platform tokens as needed
  }

  // Get token for specific platform
  static async getTokenForPlatform(platform: string): Promise<string | null> {
    switch (platform.toLowerCase()) {
      case 'facebook':
        const facebookResult = await this.getFacebookToken();
        return facebookResult.success ? facebookResult.accessToken || null : null;
      
      default:
        console.warn(`OAuth not supported for platform: ${platform}`);
        return null;
    }
  }
}

// Utility function to check if OAuth is available
export const isOAuthAvailable = (): boolean => {
  return OAuthTokenService.hasOAuthTokens();
};

// Auto-connect OAuth tokens when user logs in
export const autoConnectOAuthTokens = async (userId: string): Promise<void> => {
  try {
    await OAuthTokenService.saveOAuthTokens(userId);
    console.log('OAuth tokens auto-connected successfully');
  } catch (error) {
    console.error('Failed to auto-connect OAuth tokens:', error);
  }
};